We received the following referral:
Your Number or Email: $erTag$
Their Number: $eeTag$
Received At: $createdAt$

You should receive another message shortly letting you know who will be responsible for contacting the client.

We are honored that you would consider recommending TEAM1. We will do everything in our power to make sure that we
live up to that. If for any reason, you think that we aren't please let us know by emailing: pledge@team1.com

Thanks,
TEAM1   
